### ISSUE TITLE
Compiling statically

### ISSUE THREAD

**Issue by UnlimitedCookies** [hackerschoice/gsocket#19] opened 2021-02-05 01:30 UTC
Hey there,

I really think that gsocket is fantastic! However I was not able to configure it statically using the LDFLAG `-static`. It fails and says that no lipcrypto could be found. I am using Arch Linux with openssl installed(meaning that it includes the header files).

What am I missing? I couldn't find any documentation on compiling either. For example tor has flags specifying where to find openssl: `--openssldir=/usr/local/openssl`

Thanks in advance!

**Comment by rootTHC** [comment] 2021-02-15 13:26
I do not think -static is still feasible these days in linux when using gethostbyname and other function calls that require dynamically loaded modules.

Free beer for anyone who manages to compile gsocket or any network programm (that uses openssl and gethostbyname) staticly on any modern linux distro.

https://akkadia.org/drepper/no_static_linking.html

**Comment by rootTHC** [comment] 2021-02-15 13:46
int
main()
{
        fprintf(stderr, "helloworld\n");
        SSL_library_init();
        fprintf(stderr, "helloworld\n");
}
gcc -static -O2 -Wall -I../include/ -c x.c
gcc -static -o x x.o ../lib/libgsocket.a -lssl -lcrypto -ldl -lpthread
./x
Segmentation fault

**Comment by UnlimitedCookies** [comment] 2021-02-15 14:04
I understand that it's not a trivial task, but this makes me more curious how it is possible to compile tor statically.

I managed to compile tor statically using their `./configure --enable-static-tor --with-libevent-dir=/path/to/libevent --with-openssl-dir=/path/to/openssl --with-zlib-dir=/path/to/zlib` configure.

**Comment by rootTHC** [comment] 2021-02-15 21:57
thanks. fixed in https://github.com/hackerschoice/gsocket/tree/filexfer for now. Will move into main branch in <10 days.

./configure --enable-static --prefix=$HOME/usr
********************************** WARNING ***********************************
* Compiling STATICLY disables proper use of blitz, gs-sftp etc.              *
* Do not do it unless you know what you are doing...                         *
*                                                                            *
* Your system needs staticly compiled versions of OpenSSL etc.               *
* If in doubt compile them first:                                            *
* openssl-src>                                                               *
* ./Configure --prefix=$HOME/usr no-dso no-threads no-shared linux-generic64 *
* openssl-src> mkdir -p $HOME/usr && make all install                        *
* gsocket-src> ./configure --prefix=$HOME/usr --enable-static                *
* gsocket-src> make all install                                              *
* gsocket-src> export PATH=$HOME/usr/bin:$PATH                               *
******************************************************************************

**Comment by UnlimitedCookies** [comment] 2021-02-16 23:52
Thanks for adding the option!
I've compiled it successfully (on arch i686). [The non-static works fine btw]
However, as soon as I run `gs-netcat -l -i` I do get `Segmentation fault (core dumped)` after I have entered a secret.

The openssl binary in `$HOME/usr/bin/openssl` returns some linked objects with ldd:
```
ldd $HOME/usr/bin/openssl 
	linux-gate.so.1 (0xb7fc1000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0xb7a83000)
	libc.so.6 => /usr/lib/libc.so.6 (0xb78c3000)
	/lib/ld-linux.so.2 => /usr/lib/ld-linux.so.2 (0xb7fc3000)
```
The gs-netcat doesn't have any linked objects when checking with ldd.
I've compiled openssl with the options you provided above.

**Comment by rootTHC** [comment] 2021-02-18 12:46
What distro are you using? It's working fine here. 

Did you compile openssl as instructed with all the parameters?
./Configure --prefix=$HOME/usr no-dso no-threads no-shared linux-generic64 
make all install

then and only then compile gs-netcat:

./configure --prefix=$HOME/usr --enable-static

**Comment by UnlimitedCookies** [comment] 2021-02-18 13:25
Yep, I used the instructions you provided. But I of course replaced the
target tuple with linux-generic32. I am on archlinux32.

**Comment by rootTHC** [comment] 2021-02-18 14:20
Can you reach out to me on Telegram Channel? https://t.me/thcorg

**Comment by rootTHC** [comment] 2021-02-18 17:35
Ok. 
change this line in /etc/nsswitch.conf from

`hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns`

to

`hosts: files mymachines myhostname dns`

The correct behavior for the glibc would be to check for dynamic resolver and to gracefully return on try dns. However, the glibc just segfaults on 32bit architecture. It works fine on 64bit.

**Comment by UnlimitedCookies** [comment] 2021-03-01 22:01
Sorry for my absence.

Indeed, making the change in /etc/nsswitch.conf solved the issue! Thanks for pointing that out. Though I still don't understand why there's a difference in behavior between the architectures in the glibc.

**Comment by rootTHC** [comment] 2021-05-14 11:23
The problem is with glibc. Even when -static is used the gnu-libc uses dlopen in its libnss subsystem. It probably segfaults because nobody ever checked the i386 build if the symbols are sane or some symbols missing.

When linking against musl libc instead of gnu-libc then the binary becomes truly static again (with -static). glibc linked bins can not be static if they use gethostbyname() because glibc's libnss subsystem calls dlopen() for the resolver libs. So the two ways around this is: Use uDNS instead of gethostbyname or just compile against musl libc. The easiest is to link against musl libc on a linux distro that uses musl already (such as alpine linux).

Best advise: Compile with ./configure --enable-static on alpine/i386 and then copy the binary over to your arch32 system.

Alternatively grab a statically pre-compiled binary from [https://github.com/hackerschoice/binary/tree/main/gsocket/bin](https://github.com/hackerschoice/binary/tree/main/gsocket/bin)

**Closed by rootTHC** 2021-05-14 11:23 UTC
